### ISSUE TITLE
access to the dataset

### ISSUE THREAD

**Issue by leomiquelutti** [gmac161/practical-seismic-t21-tutorial#1]
Dear,

would it be possible to still access the Volve data, previously provided in [this link](https://github.com/gmac161/practical-seismic-t21-tutorial/blob/main/T21_Practical_Seismic_with_Python.ipynb)?

it currently sends me to a login page that I do not have the credentials.

Best regards,

**Comment by gmac161** [comment]
Hi,
The Volve data should be open so I'm not sure why you are having problems accessing the data however, [this page](https://www.equinor.com/en/what-we-do/digitalisation-in-our-dna/volve-field-data-village-download.html) 
has the following statement:
_"If you experience difficulties with downloading the data files, please contact us using email fg_DataTrawlers@equinor.com, specifying Volve Data Village in your email."_

If you are having problems with access then all I can suggest is you send an email to them as I don't have any control over the data. 
Hope this is of some help
